username: tom
install_apps:
  - thunderbird
  - steam
  - lutris
  - vlc
  - piper
install_snap_apps:
  - spotify
  - discord
install_snap_classic:
  - vscode
cli_apps:
  - fonts-firacode
  - stow
  - bat
  - exa
  - fd
  - procs
  - sd
  - ripgrep
wine_deps:
  - wine-staging
  - giflib
  - lib32-giflib
  - libpng
  - lib32-libpng
  - libldap
  - lib32-libldap
  - gnutls
  - lib32-gnutls
  - mpg123
  - lib32-mpg123
  - openal
  - lib32-openal
  - v4l-utils
  - lib32-v4l-utils
  - libpulse
  - lib32-libpulse
  - libgpg-error
  - lib32-libgpg-error
  - alsa-plugins
  - lib32-alsa-plugins
  - alsa-lib
  - lib32-alsa-lib
  - libjpeg-turbo
  - lib32-libjpeg-turbo
  - sqlite
  - lib32-sqlite
  - libxcomposite
  - lib32-libxcomposite
  - libxinerama
  - lib32-libgcrypt
  - libgcrypt
  - lib32-libxinerama
  - ncurses
  - lib32-ncurses
  - opencl-icd-loader
  - lib32-opencl-icd-loader
  - libxslt
  - lib32-libxslt
  - libva
  - lib32-libva
  - gtk3
  - lib32-gtk3
  - gst-plugins-base-libs
  - lib32-gst-plugins-base-libs
  - vulkan-icd-loader
  - lib32-vulkan-icd-loader

tabby_version: 1.0.179
pia_url: https://installers.privateinternetaccess.com/download/pia-linux-3.3.1-06924.run

devices:
  - device: /dev/nvme1n1p1
    mount: /data/games
